### ISSUE TITLE
I can't do RSPA alignment 

### ISSUE THREAD

**Issue by ElisabeteMorais** [csmsoftware/IMPaCTS#3] opened 2018-02-03 14:43 UTC
I'm new at IMPaCTS toolbox, but I can't run the funtions:  csm_rspa(spectra)
The outcome error is:

Error using doAlignment (line 18)
You cannot subscript a table using linear indexing (one subscript) or multidimensional indexing (three
or more subscripts). Use a row subscript and a variable subscript.

Error in csm_rspa/callBaseTool (line 99)
            obj.tmp = doAlignment( obj.input.spectra.X, obj.input.spectra.x_scale,
            obj.input.ref_spectrum, obj.input.normalise, obj.input.debug_interval );

Error in csm_rspa (line 58)
            obj = callBaseTool( obj )

Can you help me?

**Comment by jaketmp** [comment] 2018-02-05 09:24
Duplicate of #2

**Comment by ElisabeteMorais** [comment] 2018-02-05 10:16
Good morning,

I already that solution, and I can’t do the alignmen anyway:

model = csm_rspa(spectra)
Error using doAlignment (line 18)
You cannot subscript a table using linear indexing (one subscript) or multidimensional indexing (three
or more subscripts). Use a row subscript and a variable subscript.

Error in csm_rspa/callBaseTool (line 99)
            obj.tmp = doAlignment( obj.input.spectra.X, obj.input.spectra.x_scale,
            obj.input.ref_spectrum, obj.input.normalise, obj.input.debug_interval );

Error in csm_rspa (line 58)
            obj = callBaseTool( obj );

I don’t understand very much of this kind of language. Can you help me?

**Comment by gordondavies** [comment] 2018-02-05 14:10
Hi Elisabete,

Can you post the output of the following command? (It should print out the contents of the spectra object).

spectra

Cheers,

Gordon

**Comment by ElisabeteMorais** [comment] 2018-02-05 14:35
Hi Gordon,

The output is:
spectra =

  csm_nmr_spectra with properties:

     nmr_experiment_info: []
    nmr_calibration_info: []
           pulse_program: []
             inputparser: []
         csm_data_hashes: [0×1 containers.Map]
                       X: [65442×15 table]
                 x_scale: [65442×1 table]
            x_scale_name: 'ppm'
           is_continuous: []
              sample_ids: [1×15 string]
         sample_metadata: []
              audit_info: [1×1 csm_audit_info]
                use_hash: []
                    name: []
             sample_type: []

**Comment by gordondavies** [comment] 2018-02-05 15:05
Hi Elisabete,

In your spectra object spectra.X and spectra.x_scale are tables.

The supported data types for these variables are matrices:

`spectra.X `- m*n matrix. (m = samples (rows), n = intensity values (columns).

`spectra.x_scale` - 1*n matrix (1 row, with 1 column per ppm value).

For example, a test spectra with 48 samples and 19272 ppm scale has the following output:
```
 X: [48×19272 double]
 x_scale: [1×19272 double]
```

The csm_rspa object is expecting the spectra object X and x_scale values to be these kinds of data types, not a table.

You can find more information on the datatypes required here:

https://csmsoftware.github.io/docs/impacts/csm_nmr_spectra.html

Best wishes,

Gordon

**Closed as completed** 2018-02-05 15:21 UTC
